### PR TITLE
More Library and Loadout page fixes

### PR DESCRIPTION
**Pull request by erri120**
- formatted dates with ticker
- indeterminate state in loadout page (currently broken)
- implements #1971
- can install multiple loadout items at once

### CODE REVIEW

**Review by Al12rs — COMMENTED** [review]
I'm getting an exception on clean load after adding a couple of items:

```
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Avalonia.Controls.Models.TreeDataGrid.TextCell`1.set_Text(String value) in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/TextCell.cs:line 52
   at Avalonia.Controls.Primitives.TreeDataGridTextCell.set_Value(String value) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridTextCell.cs:line 58
   at Avalonia.Controls.Primitives.TreeDataGridTextCell.OnModelPropertyChanged(Object sender, PropertyChangedEventArgs e) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridTextCell.cs:line 106
   at Avalonia.Controls.Models.NotifyingBase.RaisePropertyChanged(String propertyName) in /_/src/Avalonia.Controls.TreeDataGrid/Models/NotifyingBase.cs:line 28
   at Avalonia.Controls.Models.NotifyingBase.RaiseAndSetIfChanged[T](T& field, T value, String propertyName) in /_/src/Avalonia.Controls.TreeDataGrid/Models/NotifyingBase.cs:line 19
   at Avalonia.Controls.Models.TreeDataGrid.TextCell`1.set_Value(T value) in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/TextCell.cs:line 60
   at Avalonia.Controls.Models.TreeDataGrid.TextCell`1.<.ctor>b__7_0(BindingValue`1 x) in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/TextCell.cs:line 38
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at Avalonia.Experimental.Data.Core.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Controls.TreeDataGrid/Experimental/Data/Core/LightweightObservableBase.cs:line 138
   at Avalonia.Experimental.Data.Core.TypedBindingExpression`2.PublishValue() in /_/src/Avalonia.Controls.TreeDataGrid/Experimental/Data/Core/TypedBindingExpression`2.cs:line 285
   at Avalonia.Experimental.Data.Core.TypedBindingExpression`2.ChainPropertyChanged(Object sender) in /_/src/Avalonia.Controls.TreeDataGrid/Experimental/Data/Core/TypedBindingExpression`2.cs:line 322
   at Avalonia.Experimental.Data.Core.TypedBindingExpression`2.ChainPropertyChanged(Object sender, PropertyChangedEventArgs e) in /_/src/Avalonia.Controls.TreeDataGrid/Experimental/Data/Core/TypedBindingExpression`2.cs:line 325
   at Avalonia.Utilities.WeakEventHandlerManager.Subscription`2.OnEvent(Object sender, T eventArgs)
   at R3.BindableReactiveProperty`1.OnValueChanged(T value)
   at R3.ReactiveProperty`1.set_Value(T value)
   at R3.BindableReactiveProperty`1.set_Value(T value)
   at NexusMods.App.UI.Pages.LibraryPage.NexusModsModPageLibraryItemModel.<>c.<.ctor>b__1_1(Int32 _, NexusModsModPageLibraryItemModel model) in C:\Dev\Repos\NexusMods.App\src\NexusMods.App.UI\Pages\LibraryPage\NexusModsModPageLibraryItemModel.cs:line 24
   at R3.AnonymousObserver`2.OnNextCore(T value)
   at R3.Observer`1.OnNext(T value)
```

image

From just reading the stack trace it seems it is trying to update back the bound value, as if it was a two way binding?

**Review by Al12rs — COMMENTED** [review]
If you select both parent and child in Loadout View, then press Remove button, you get a null ref exception:
image
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source)
   at NexusMods.App.UI.Pages.LoadoutPage.LoadoutViewModel.<.ctor>b__13_5(Unit _, CancellationToken cancellationToken) in C:\Dev\Repos\NexusMods.App\src\NexusMods.App.UI\Pages\LoadoutPage\LoadoutViewModel.cs:line 83
```

**Review by Al12rs — CHANGES_REQUESTED** [review]
See problems listed above. 
Another thing that needs fixing, but might be for future PRs is how to handle cell entries for parent rows in the case of multiple children:
image

We can look at the exceptions in a call if you'd like

**Comment by erri120** [comment]
@Al12rs 
> If you select both parent and child in Loadout View, then press Remove button, you get a null ref exception

I can't repro this.

**Comment by Al12rs** [comment]
> @Al12rs
> 
> > If you select both parent and child in Loadout View, then press Remove button, you get a null ref exception
> 
> I can't repro this.

Might need to try with both local items and nexus download items perhaps. I could get it to reproduce quire reliably. 
Maybe it was fixed with the previous commit

**Review by Al12rs — APPROVED** [review]

**Pull request merged**
