### PR TITLE
Add `GameStore` to `GameInstallation`

### PR DESCRIPTION
**Pull request by erri120**
Replaces #133

Adds a `GameStore` value to `GameInstallation`, which is needed for #42 and other game support code that requires different functionality depending on the store.

Since this PR changes how `GameInstallation` is serialized, all tests that use pre-exported loadouts will fail. #253 added helpers for testing, which should be used instead of so pre-exported loadouts.

### CODE REVIEW

**Comment by Sewer56** [comment]
Oh? An edge case?

Alright; let me throw in a completely unrelated edge case of my own.
There are some games where the expected ***Current Working Directory*** is ***NOT*** the EXE/main binary folder.

Will make issue post sprint; I've a tiny backlog of issues to write.

**Comment by erri120** [comment]
> Another important note, `AGame.PrimaryFile` can't be store agnostic in some cases. For example, Bannerlord differs in the binary path (`bin/Win64_Shipping_Client` on Steam/GOG/Epic vs `bin/Gaming.Desktop.x64_Shipping_Client` on Xbox), so it needs to be removed or replaced with something like
> 
> ```cs
> public abstract GamePath GetPrimaryFile(GameInstallation installation);
> ```

This is also the case for Stardew Valley (#42), the primary file changes depending on operating system **and** store.

**Comment by Aragas** [comment]
As a side note related to the UI, showing the store in the game list would also be helpful

**Comment by halgari** [comment]
This might be fixed after merging #273

**Comment by erri120** [comment]
`NexusMods.Games.BethesdaGameStudio.Tests` and `NexusMods.UI.Tests` are still failing because they use pre-exported loadouts.

**Comment by erri120** [comment]
After #273, #279 and some manual changes, all pre-exported loadouts have been removed, and all tests pass "on my machine".

**Review by halgari — APPROVED** [review]

**Pull request merged**
