### PR TITLE
Configure INI parser to support bethesda ini files

### LINKED ISSUE #448: Install fail due to Ini Analyzer exception if ini files contain comments
Investigate exception:

```
Error analyzing C:/Users/Al12r/AppData/Local/Temp/NexusMods.App-7901cbff-1e8c-48f9-a2ef-7897aef75ecd/00cacd02-b1ff-441f-9bf9-a4b732c428f9/Character Creation/Randomizer/In Sync/meshes/actors/character/BodyGenData/XPMSE.esp/templates.ini with IniAnalzyer|IniParser.Exceptions.ParsingExcept
ion: Unknown file format. Couldn't parse the line: '#Arrow'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0 while parsing line number 1 with value '#Arrow' - IniParser version: 2.5.2.0
 ---> IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: '#Arrow'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0
   at IniParser.Parser.IniDataParser.ProcessLine(String currentLine, IniData currentIniData)
   at IniParser.Parser.IniDataParser.Parse(String iniDataString)
   --- End of inner exception stack trace ---
   at IniParser.Parser.IniDataParser.Parse(String iniDataString)
   at IniParser.StreamIniDataParser.ReadData(StreamReader reader)
   at NexusMods.Games.Generic.FileAnalyzers.IniAnalzyer.AnalyzeAsync(FileAnalyzerInfo info, CancellationToken token)+MoveNext() in C:\Dev\Repos\NexusMods.App\src\Games\NexusMods.Games.Generic\FileAnalyzers\IniAnalzyer.cs:line 22
   at NexusMods.Games.Generic.FileAnalyzers.IniAnalzyer.AnalyzeAsync(FileAnalyzerInfo info, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NexusMods.DataModel.ArchiveAnalyzer.AnalyzeFileInnerAsync(IStreamFactory sFn, CancellationToken token, Int32 level, Hash parent, Nullable`1 parentArchivePath, RelativePath parentPath, String fileName) in C:\Dev\Repos\NexusMods.App\src\NexusMods.DataModel\ArchiveAnalyzer.cs:line 193
   at NexusMods.DataModel.ArchiveAnalyzer.AnalyzeFileInnerAsync(IStreamFactory sFn, CancellationToken token, Int32 level, Hash parent, Nullable`1 parentArchivePath, RelativePath parentPath, String fileName) in C:\Dev\Repos\NexusMods.App\src\NexusMods.DataModel\ArchiveAnalyzer.cs:line 193
```

### PR DESCRIPTION
**Pull request by Al12rs**
fixes #448 

Configuration taken from Mutagen:
https://github.com/Noggog/Mutagen/blob/369a0549fab90593cb130b3889f988228f8ecf98/Mutagen.Bethesda.Core/Archives/DI/GetArchiveIniListings.cs#L38-L46

Tested with ENB for Legendary edition.

### CODE REVIEW

**Review by erri120 — APPROVED** [review]

**Comment by erri120** [comment]
Should probably add some tests for this.

**Comment by Al12rs** [comment]
> Should probably add some tests for this.

**Review by erri120 — CHANGES_REQUESTED** [review]
Should have some tests for the config.

**Comment by erri120** [comment]
> > Should probably add some tests for this.
> 
> Something like installing a mod with a "bad" ini file?

You can make the settings object internal and create a test that has various `ini` files as input and just test if that works.

**Comment by Al12rs** [comment]
That assumes I know all the "interesting" cases for inis to fail. What are we checking for exactly? 
Is this for the goal of regression testing or more to see if we are covering all the cases we want?

**Comment by erri120** [comment]
> That assumes I know all the "interesting" cases for inis to fail. What are we checking for exactly? Is this for the goal of regression testing or more to see if we are covering all the cases we want?

On `main`, the INI analyzer fails because it can't deal with a comment (#448). You can create a test with an INI file that contains a comment, which should fail on `main` and succeed on your branch.

**Comment by Al12rs** [comment]
Added a test for this

**Review by erri120 — APPROVED** [review]

**Pull request merged**
