### PR TITLE
Settings Backend

### LINKED ISSUE #396: Settings - Implement Settings Backend
Using the modern [Configuration](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration) approach, components in our DI system can require `IOption<MyOptions>` or `IOptionMonitor<MyOptions>` to access component-specific configuration without having to deal with loading, saving and updating them. The monitor is especially useful as it's fully reactive and allows for changes to be applied immediately (see #362 for an example).

These settings/options should be saved to disk as JSON to be persistent, but should also be presented to the user in some capacity. Such a system would provide implementations of `IOptionMonitor<T>` and serve as a configuration provider.

- #1182

### PR DESCRIPTION
**Pull request by erri120**
Part of #1182, resolves #396.

Initial implementation of the settings backend:

- Adds `ISettings` for all setting types.
- Adds `ISettingsManager` to get or change settings.
- Adds `ISettingsBuilder` to configure how settings appear in the UI.

Missing from this PR that are done in a separate PR as part of #1182:

- Moving existing setting types to the backend
- Persisting and loading the settings
- Allowing the user to change the settings via a UI

### CODE REVIEW

**Comment by halgari** [comment]
This all looks solid to me. Any thoughts on localization with this? I assume that's on the UI side?

I thought we might want the `Set` methods to be async, but now that I think about it, we can cache those values, and have a background task that syncs the settings to disk, no reason to make the `Set` call async just to wait for a disk write.

**Review by halgari — APPROVED** [review]

**Comment by Al12rs** [comment]
Do you have examples of when we might want to use settings without UI? 
It's effectively a key value store at that point, for simple values at least, but we may still need to configure the backing store for them.
Should we consider using this for things like saving visual UI state ( #1043 e.g. what column the user last sorted the mod file tree by)

**Comment by erri120** [comment]
> This all looks solid to me. Any thoughts on localization with this? I assume that's on the UI side?

`WithDisplayName` and `WithDescription` take strings, so you can just use resources, and it'll work just fine.

**Comment by erri120** [comment]
> Do you have examples of when we might want to use settings without UI? It's effectively a key value store at that point, for simple values at least, but we may still need to configure the backing store for them. Should we consider using this for things like saving visual UI state ( #1043 e.g. what column the user last sorted the mod file tree by)?

#1043 can definitely benefit from this. Ideally, every kind of setting we have should move to this backend.

**Pull request merged**
