### PR TITLE
Added a page for Cyberpunk to dev docs

### PR DESCRIPTION
**Pull request by Pickysaurus**
Hidden developer docs for games we don't support yet.

### CODE REVIEW

**Comment by Pickysaurus** [comment]
image

**Comment by erri120** [comment]
You can delete the other files for games we currently don't support.

**Comment by Pickysaurus** [comment]
> You can delete the other files for games we currently don't support.

I left them commented out as I felt it wasn't worth losing this research we've already done. Unless you think we'll have to do this all over again when we revisit those games?

**Comment by erri120** [comment]
> > You can delete the other files for games we currently don't support.
> 
> I left them commented out as I felt it wasn't worth losing this research we've already done. Unless you think we'll have to do this all over again when we revisit those games?

We've deleted the projects for those games as well. Everything is stored in git, we can easily go back in time and retrieve the data.

**Comment by Pickysaurus** [comment]
@erri120 Deleted the files as suggested.

**Review by insomnious — APPROVED** [review]

**Pull request merged**
