### PR TITLE
UI styling rework

### LINKED ISSUE #721: Text is mis-aligned in the download progress screen
strange text

On the right hand side "2 min" and "remaining" are misaligned.

### LINKED ISSUE #735: UI style consolidation
# Epic

## Issues

- [x] create a separate UI project for only styles, resources and components
- [x] Convert `Nexus.xaml` (Style) to resources dictionaries (#736)
  - [x] Remove all uses of `Nexus.xaml` and use the new resources
- [ ] ~~Use Control Themes~~ (We ended up using Style Classes)
  - [x] #734
- [x] Consolidate icons
- [x] Remove global styles
- [x] Look into Text centering issues (line height related problems)
- [x] Consolidate Text styles
- [x] Cleanup

### PR DESCRIPTION
**Pull request by Al12rs**
Closes #735 
Closes #721 

This moves all our Styles to a dedicated Theme project, where Style classes are mostly being used.

# Changes:
- Created dedicated Theme project
- Introduced new 3 layer Color system from Figma
- Introduced new Opacity layer system
- Implemented a ColorPalette for Avalonia Fluent Theme that provides good default foreground and background colors
- Consolidated Typography
    - Fixed a number of issues with Text styles, found cause of alignment issues (Avalonia Bug)
- Added many scattered icons to IconsStyles
- Added ADR for Styling approach choices
- Added Styling guidelines documentation
- Moved App.axaml from App.UI project to App project, to avoid Circular dependency App.UI -> Theme -> App.UI
- Added way to define BoxShadows using resources for colors instead of color literals
- Moved all Styling found in UI files to Theme project
- Moved all other existing styles to Theme project
- Reorganized folder structures for Styles in theme project for better organization
- Fixed and improved a whole bunch of styles (basically all of them). Some completely redone
- Removed old styles and old resources

### CODE REVIEW

**Comment by Al12rs** [comment]
Fomod installer styling seems to be broken, I think I missed it. Will add that to the PR.

**Comment by erri120** [comment]
When opening the app for the first time

**Comment by Al12rs** [comment]
Fomod Stuff should be added now

**Review by erri120 — CHANGES_REQUESTED** [review]
The telemetry overlay needs to be fixed, and we should also look into getting auto-completion working.

**Review by erri120 — APPROVED** [review]

**Pull request merged**
