### PR TITLE
Display Mods in a datagrid in the app

### PR DESCRIPTION
**Pull request by halgari**
The following features are implemented:

* Shows mods in a completely reactive manner
  * Mods enabled/disabled in other instances of the app (or the CLI) show up in the app in realtime
  * The "Installed" column refreshes roughly once a minute shows the delta since the mod was installed in a humanized manner (one second, one hour, 2 days, etc.)
* Columns can be sorted
* Columns can be reordered 
* Switching the active loadout switches the displayed mods
* Entities in the DataStore now use a LRU cache of 10,000 items this greatly improves load performance of the UI, we can tweak this cache in the future (perhaps with a weak reference cache, that's really the semantics we want here)

NexusMods App_htgzbzLXKC

DataGrids are a massive pain in any UI framework and Avalonia is no exception. Essentially what I ended up doing is creating a Interface/DesignVM/VM/View combo for *every column* in the data grid, hence the explosion of classes. While this sucks from a filecount standpoint the end effect is that we can prototype the grid in the designer, have custom controls in the grid, and do all that via ReactiveUI instead of switching to Bindings for only this one use case. So it's an explosion of file counts but the code remains consistent through the app. 

I also parented the VMs under their interface, so in the IDE you can collapse the VMs and get a much cleaner project overview:

projectoverview

All in all this worked out fairly well, and you'll see a pattern in the madness that is this large PR. 4 files per column, 5 columns = 20 files, plus a handful of abstraction files.

### CODE REVIEW

**Comment by erri120** [comment]
Trying to drag a column around on Linux crashes the application. This is probably just an issue with Avalonia itself: https://github.com/avaloniaUI/Avalonia/issues?q=is%3Aissue+System.InvalidOperationException%3A+The+control+already+has+a+visual+parent.

```txt
Unhandled exception. System.InvalidOperationException: The control already has a visual parent.
   at Avalonia.Visual.ValidateVisualChild(Visual c) in /_/src/Avalonia.Base/Visual.cs:line 638
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 489
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 576
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in /_/src/Avalonia.Controls/Grid.cs:line 1098
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in /_/src/Avalonia.Controls/Grid.cs:line 1053
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in /_/src/Avalonia.Controls/Grid.cs:line 501
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 576
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in /_/src/Avalonia.Controls/Grid.cs:line 1098
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in /_/src/Avalonia.Controls/Grid.cs:line 1053
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in /_/src/Avalonia.Controls/Grid.cs:line 501
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 576
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 51
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Border.cs:line 241
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 576
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 576
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Primitives.DataGridColumnHeadersPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls.DataGrid/Primitives/DataGridColumnHeadersPresenter.cs:line 406
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 576
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 297
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 257
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 244
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 175
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at NexusMods.App.UI.Startup.Main(IServiceProvider provider, String[] args) in /home/florian/projects/NexusMods.App/src/NexusMods.App.UI/Startup.cs:line 14
   at NexusMods.App.Program.Main(String[] args) in /home/florian/projects/NexusMods.App/src/NexusMods.App/Program.cs:line 52
   at NexusMods.App.Program.<Main>(String[] args)
```

**Comment by halgari** [comment]
> Trying to drag a column around on Linux crashes the application. This is probably just an issue with Avalonia itself

Likely, moving columns isn't part of the original requirements, so I'll disable it for now and we can loop around later once Avalonia 11 officially releases

**Comment by erri120** [comment]
The mod enable switch feels very sluggish. It has two problems:

1) On first render: the switch is set to false initially, after it has rendered, RxUI will check the bindings and switch the toggle to true, if the mod is enabled (can be seen in the gif posted above). The component also re-renders when changing the sorting, which also has a delay after rendering.
2) When toggling: `ToggleEnabledCommand` is not a "cheap" method. It might not be very noticeable on high end machines, but there is a 1/2 second delay after toggling, before the switch actually updates.

[out.webm](https://user-images.githubusercontent.com/16577545/229211952-7c52f700-487a-45bc-9e99-91ee93e484ce.webm)

**Review by erri120 — APPROVED** [review]
Aside from some performance issues we can tackle later, LGTM.

**Comment by halgari** [comment]
Yep, we'll want to make a performance pass on this in the future.

**Pull request merged**
