### PR TITLE
Update `TemporaryFileManager`

### LINKED ISSUE #239: Update `TemporaryFileManager` to use `IFileSystem`

### PR DESCRIPTION
**Pull request by erri120**
Resolves #239 

Updates `TemporaryFileManager` to use `IFileSystem`. Importantly, this PR also updates `InMemoryFileSystem` and implements _almost_ all `FileMode` values (`FileMode.Append` is missing).

### CODE REVIEW

**Review by Sewer56 — APPROVED** [review]
LGTM

**Comment by erri120** [comment]
Weird exception:

```log
2023-04-03T09:59:51.4312265Z [xUnit.net 00:01:21.30] NexusMods.DataModel.Tests: Catastrophic failure: System.IO.IOException: The process cannot access the file '1e471f37-9f82-4cc0-8b81-4296825fbb3c.tmp' because it is being used by another process.
2023-04-03T09:59:51.4313579Z    at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
2023-04-03T09:59:51.4314291Z    at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
2023-04-03T09:59:51.4315182Z    at NexusMods.Paths.FileSystem.InternalDeleteDirectory(AbsolutePath path, Boolean recursive) in D:\a\NexusMods.App\NexusMods.App\src\NexusMods.Paths\FileSystemAbstraction\RealFileSystem\FileSystem.cs:line 129
2023-04-03T09:59:51.4316261Z    at NexusMods.Paths.BaseFileSystem.DeleteDirectory(AbsolutePath path, Boolean recursive) in D:\a\NexusMods.App\NexusMods.App\src\NexusMods.Paths\FileSystemAbstraction\BaseFileSystem.cs:line 272
2023-04-03T09:59:51.4317248Z    at NexusMods.Paths.TemporaryFileManager.Dispose_Impl() in D:\a\NexusMods.App\NexusMods.App\src\NexusMods.Paths\TemporaryFileManager.cs:line 48
2023-04-03T09:59:51.4318134Z    at NexusMods.Paths.TemporaryFileManager.Dispose() in D:\a\NexusMods.App\NexusMods.App\src\NexusMods.Paths\TemporaryFileManager.cs:line 37
2023-04-03T09:59:51.4319094Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
2023-04-03T09:59:51.4319989Z --- End of stack trace from previous location ---
2023-04-03T09:59:51.4320522Z    at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|16_0(Object o)
2023-04-03T09:59:51.4321158Z    at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
2023-04-03T09:59:51.4321742Z    at Xunit.DependencyInjection.HostManager.Dispose()
2023-04-03T09:59:51.4322350Z    at Xunit.Sdk.DisposalTracker.Dispose() in /_/src/xunit.execution/Sdk/DisposalTracker.cs:line 29
2023-04-03T09:59:51.4323017Z    at Xunit.Sdk.TestFrameworkExecutor`1.Dispose() in /_/src/xunit.execution/Sdk/Frameworks/TestFrameworkExecutor.cs:line 72
2023-04-03T09:59:51.4323765Z    at DisposableExtensions.SafeDispose(IDisposable disposable) in /_/src/xunit.runner.utility/Extensions/DisposableExtensions.cs:line 8
2023-04-03T09:59:51.4324433Z    at Xunit.Xunit2.Dispose() in /_/src/xunit.runner.utility/Frameworks/v2/Xunit2.cs:line 86
2023-04-03T09:59:51.4325083Z    at Xunit.XunitFrontController.Dispose() in /_/src/xunit.runner.utility/Frameworks/XunitFrontController.cs:line 155
2023-04-03T09:59:51.4326238Z    at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in /_/src/xunit.runner.visualstudio/VsTestRunner.cs:line 622
2023-04-03T09:59:52.3652629Z 
2023-04-03T09:59:52.3653735Z Passed!  - Failed:     0, Passed:    29, Skipped:     0, Total:    29, Duration: 1 m 18 s - NexusMods.DataModel.Tests.dll (net7.0)
```

**Comment by Sewer56** [comment]
Since it happened on DataModel test, maybe it's related to the thing I found and fixed in the FOMOD branch last week.

Currently closing the `SqliteDataStore` wouldn't dispose the underlying handle.

**Comment by erri120** [comment]
The exception originates from `Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()`:



https://github.com/dotnet/runtime/blob/24fa97ab99b4a63f638f63a90ae83c4b80772114/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs#L122

I'm not sure on the ordering of this and why there are two `SqliteIPC` entries.

**Comment by erri120** [comment]
I think the main issue is having two `SqliteIPC` entries and having different implementations for memory mapped files depending on the OS. Windows is probably more sensible to the IO stuff and throws an exception.

**Comment by erri120** [comment]
From MS docs:

> If an object's Dispose method is called more than once, the object must ignore all calls after the first one. The object must not throw an exception if its Dispose method is called multiple times. Instance methods other than Dispose can throw an ObjectDisposedException when resources are already disposed.

https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?redirectedfrom=MSDN&view=netframework-4.7.2#System_IDisposable_Dispose

**Review by halgari — APPROVED** [review]
Yep, adding an ignore to these is great

**Comment by Sewer56** [comment]
We should probably merge this before we start running into merge conflicts 😉

**Comment by erri120** [comment]
I did a rebase with latest changes on main.

**Pull request merged**
