### PR TITLE
Cleanup: remove activities

### PR DESCRIPTION
**Pull request by erri120**
This was mostly just deleting things, except for the login overlay, which was the only non-deprecated part of the app that was still using the activity system.

### CODE REVIEW

**Review by halgari — CHANGES_REQUESTED** [review]
I can log out via the code on `main` but with this PR it doesn't update the UI when logging out. I think it does log out (says so in the log) but the UI doesn't update and my avatar remains in the top right

**Comment by erri120** [comment]
> I can log out via the code on `main` but with this PR it doesn't update the UI when logging out. I think it does log out (says so in the log) but the UI doesn't update and my avatar remains in the top right

Can't repro this. I also didn't touch the code to log out, that has remained the same. Maybe you have an old datastore?

**Comment by Al12rs** [comment]
I tested this and it seems to be working fine, not issues logging in, logging out, then logging back in. I tested both without restarts of the app and with restarts.

**Review by Al12rs — APPROVED** [review]
Tested only

**Review by halgari — APPROVED** [review]
LGTM

**Pull request merged**
