### PR TITLE
`EmptyState` control and diagnostic page fixes

### LINKED ISSUE #1585: Diagnostics page design fixes
Diagnostic items in the list are still not the correct height. The content of the items should have 12px of padding on all sides. They should each have drop shadow small applied.

Currently looks like this:

Image

Should look like this:

Figma link

Image

https://www.figma.com/design/hsUiqro210T3tsK1F9l1fQ/%F0%9F%93%B1%F0%9F%A9%BAHealth-check?node-id=1-2954&t=wgNtrLWN8J36plMa-1

## Empty state

Change text to: Your loadout passed the health check without issues. Ready for gaming.

[Figma design](https://www.figma.com/design/hsUiqro210T3tsK1F9l1fQ/%F0%9F%93%B1%F0%9F%A9%BAHealth-check?node-id=111-2468&t=wgNtrLWN8J36plMa-1)

Image

### LINKED ISSUE #1600: Create empty state component
Should be implemented with a custom control that works something like this:

```xaml
<Foo>
  <Foo.EmptyMessage>
    <TextBlock>You've got nothing here</TextBlock>
  </Foo.EmptyMessage>

  <TextBlock>There is something here</TextBlock>
</Foo>
```

https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=1788-6453&t=vTR45Pqi1V8KWQrh-1

### PR DESCRIPTION
**Pull request by erri120**
Resolves #1585:

New `EmptyState` control, resolves #1600:

### CODE REVIEW

**Comment by captainsandypants** [comment]
@erri120 Is the padding on the diagnostic items supposed to be corrected on this build? They look the same to me

**Comment by erri120** [comment]
> @erri120 Is the padding on the diagnostic items supposed to be corrected on this build? They look the same to me

I changed the padding as described in the issue #1585.

**Review by Al12rs — COMMENTED** [review]
Looking at the code I'm not sure if EmptyState control is really reducing conde complexity or making adding an empty state particularly easier.
If you need a slightly different format, it doesn't seem to be saving a lot of lines. 
The structure is a bit weird with it containing both the empty and the non empty states, so I'm not sure readability is improved.

**Comment by erri120** [comment]
> Looking at the code I'm not sure if EmptyState control is really reducing conde complexity or making adding an empty state particularly easier. If you need a slightly different format, it doesn't seem to be saving a lot of lines. The structure is a bit weird with it containing both the empty and the non empty states, so I'm not sure readability is improved.

I think it massively simplifies the code. `DiagnosticListView` is a great example of this, as it only takes 10 lines to have a working, and properly styled empty state.

**Comment by erri120** [comment]
Here's a before (notice that it doesn't even fit):



And after:

**Comment by Al12rs** [comment]
But `EmptyState` was created ad hoc for `DiagnosticListView`, does it really simplify the other places where the structure needs to be slightly different?

**Comment by erri120** [comment]
> But `EmptyState` was created ad hoc for `DiagnosticListView`, does it really simplify the other places where the structure needs to be slightly different?

It wasn't created ad-hoc. It was created for #1600, and with designs by @captainsandypants. It's a design component that should have a matching App control.

**Review by captainsandypants — APPROVED** [review]
UI looks good.

**Pull request merged**
